### PR TITLE
Add HTML Section and JalanJalan Landing Page

### PR DESCRIPTION
**Pull request by alfianandinugraha**
Add JalanJalan landing page

Demo: https://alfianandinugraha.github.io/jalanjalan/
Original Repo: https://github.com/alfianandinugraha/jalanjalan

### CODE REVIEW

**Review by rimzzlabs — COMMENTED** [review]
Boleh tambahin project list di readme.MD nya?

**Comment by alfianandinugraha** [comment]
Okeyyy

**Comment by rimzzlabs** [comment]
sip, done

**Comment by alfianandinugraha** [comment]
Thank youu 👍

**Pull request merged**
